PROJECT(test)

if (MSVC)
find_package(libmysql CONFIG REQUIRED)
elseif (CMAKE_COMPILER_IS_GNUCXX)
INCLUDE_DIRECTORIES(/usr/include/mysql)
LINK_DIRECTORIES(/usr/lib64/mysql)
endif (MSVC)
find_package(openssl CONFIG REQUIRED)

AUX_SOURCE_DIRECTORY(${PROJECT_SOURCE_DIR}/src test_src)

ADD_EXECUTABLE(${PROJECT_NAME} ${test_src})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE wsCore)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE wsDatabase)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE wsNetwork)

if (MSVC)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE libmysql)
else (CMAKE_COMPILER_IS_GNUCXX)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE mysqlclient)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE crypto)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE pthread)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE dl)
endif (MSVC)
