PROJECT(test)

AUX_SOURCE_DIRECTORY(${PROJECT_SOURCE_DIR}/src test_src)

ADD_EXECUTABLE(${PROJECT_NAME} ${test_src})
TARGET_LINK_LIBRARIES(${PROJECT_NAME}
	PRIVATE
		wsCore
		wsDatabase
		wsNetwork
)

if (CMAKE_COMPILER_IS_GNUCXX)
	TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE dl)
endif()
